# Generated by Django 5.2.8 on 2025-11-26 11:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.TextField()),
                ('full_name', models.TextField()),
                ('role', models.CharField(choices=[('admin', 'admin'), ('employee', 'employee')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'active'), ('disabled', 'disabled'), ('pending', 'pending')], default='active', max_length=20)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
                'ordering': ['created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refresh_token', models.TextField(unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_sessions',
                'managed': False,
            },
        ),
    ]
